[project]
name = "tg_notifier_backend"
version = "0.1.0"
description = "Enterprise Telegram Notifier Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "asyncpg",
    "psycopg2-binary",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
    "sqlmodel>=0.0.18",
    "slowapi"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Явно указываем структуру пакета для hatchling
[tool.hatch.build]
include = [
    "app/**/*.py",
    "app/**/*.json",
    "app/**/*.yaml",
    "app/**/*.yml",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-bdd>=7.0.0",
    "httpx>=0.24.0",
    "pytest-mock>=3.0.0",
    "requests>=2.25.0",
]